plugins {
    id 'java'
    id 'jacoco'
    id 'application'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
description = 'JukeBox Music Player'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

application {
    mainClass = 'com.Luv.juckbox.App'
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter:5.12.2'
    testImplementation 'com.github.stefanbirkner:system-lambda:1.2.1'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
    useJUnitPlatform()
}